"use client";

import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence, useReducedMotion } from "framer-motion";
import VideoModal from "./VideoModal";

// --- Types & Data ---
type Category = "Product Demo" | "Walkthroughs" | "AI Movie" | "Use Cases";

interface VideoItem {
    id: string;
    category: Category;
    title: string;
    subtitle?: string;
    duration?: string;
    posterImage: string;
    previewVideoSrc: string;
    fullVideoSrc: string;
}

const CATEGORIES: Category[] = ["Product Demo", "Walkthroughs", "AI Movie", "Use Cases"];

// REPLACE THESE URLs WITH ACTUAL EXBABEL VIDEOS AND POSTERS LATER
const VIDEO_DATA: VideoItem[] = [
    {
        id: "demo-1",
        category: "Product Demo",
        title: "Meet Exbabel",
        subtitle: "Watch how Exbabel translates live speech to texts & audio instantly.",
        duration: "2:15",
        posterImage: "/photos/exbabel product video picture.png",
        previewVideoSrc: "https://www.youtube.com/embed/rNwDGQVu_o0?autoplay=1&mute=1&controls=0&loop=1&playlist=rNwDGQVu_o0",
        fullVideoSrc: "https://www.youtube.com/embed/rNwDGQVu_o0?autoplay=1",
    },
    {
        id: "demo-3",
        category: "Product Demo",
        title: "Meet the Pastor",
        subtitle: "An AI Showcase of our Exbabel Platform",
        duration: "1:10",
        posterImage: "/photos/pastor showcase.png",
        previewVideoSrc: "https://www.youtube.com/embed/O-5FYsfVNY4?autoplay=1&mute=1&controls=0&loop=1&playlist=O-5FYsfVNY4",
        fullVideoSrc: "https://www.youtube.com/embed/O-5FYsfVNY4?autoplay=1",
    },
    {
        id: "demo-2",
        category: "Product Demo",
        title: "Meet the Platform",
        subtitle: "Step-by-step guide to streaming a multi-lingual session.",
        duration: "1:45",
        posterImage: "/photos/settings up your firs broadcast.png",
        previewVideoSrc: "https://www.youtube.com/embed/IEAedQlehMY?autoplay=1&mute=1&controls=0&loop=1&playlist=IEAedQlehMY&start=8",
        fullVideoSrc: "https://www.youtube.com/embed/IEAedQlehMY?autoplay=1",
    },
    {
        id: "demo-4",
        category: "Product Demo",
        title: "Meet the Users",
        duration: "3:05",
        posterImage: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        previewVideoSrc: "",
        fullVideoSrc: "",
    },

    {
        id: "walk-1",
        category: "Walkthroughs",
        title: "Admin Dashboard Tour",
        subtitle: "Navigate the admin panel effectively.",
        duration: "4:00",
        posterImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        previewVideoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
        fullVideoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    },
    {
        id: "ai-1",
        category: "AI Movie",
        title: "The Future of Language",
        subtitle: "A short film generated by our AI.",
        duration: "5:30",
        posterImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        previewVideoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        fullVideoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    },
    {
        id: "use-1",
        category: "Use Cases",
        title: "Churches & Ministries",
        subtitle: "Reaching broader congregations.",
        duration: "2:20",
        posterImage: "https://images.unsplash.com/photo-1438283173091-5dbf5c5a3206?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        previewVideoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
        fullVideoSrc: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    }
];

export default function VideoLibrarySection() {
    const [activeCategory, setActiveCategory] = useState<Category>("Product Demo");

    // Filter videos for the current category, limit to 4 if possible
    const currentVideos = VIDEO_DATA.filter((v) => v.category === activeCategory).slice(0, 4);
    const [activeCardId, setActiveCardId] = useState<string | null>(null);
    const [modalVideoId, setModalVideoId] = useState<string | null>(null);

    // Initialize active card when category changes
    useEffect(() => {
        if (currentVideos.length > 0) {
            setActiveCardId(currentVideos[0].id);
        }
    }, [activeCategory]);

    const activeVideo = VIDEO_DATA.find(v => v.id === modalVideoId);

    return (
        <section className="relative py-24 bg-white overflow-hidden font-sans border-t border-gray-100">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Header & Tabs */}
                <div className="flex flex-col items-center mb-12 md:mb-16">
                    <div className="inline-flex items-center rounded-full border border-blue-100 bg-blue-50/50 px-3 py-1 mb-6">
                        <span className="text-sm font-semibold tracking-tight text-blue-600">
                            Video Library
                        </span>
                    </div>
                    <h2 className="text-3xl md:text-5xl font-extrabold text-gray-900 tracking-tight mb-8 text-center max-w-3xl">
                        See Exbabel in Action
                    </h2>


                </div>

                {/* Gallery */}
                <div className="flex flex-nowrap gap-3 md:gap-4 h-[450px] md:h-[500px] overflow-x-auto md:overflow-visible snap-x snap-mandatory pb-6 md:pb-0 px-4 md:px-0 -mx-4 md:mx-0 scrollbar-hide">
                    {currentVideos.map((video) => {
                        const isActive = activeCardId === video.id;

                        return (
                            <VideoCard
                                key={video.id}
                                video={video}
                                isActive={isActive}
                                onMouseEnter={() => setActiveCardId(video.id)}
                                onFocus={() => setActiveCardId(video.id)}
                                onClick={() => setModalVideoId(video.id)}
                            />
                        );
                    })}
                </div>
            </div>

            <VideoModal
                isOpen={!!modalVideoId}
                onClose={() => setModalVideoId(null)}
                videoSrc={activeVideo?.fullVideoSrc || ""}
                title={activeVideo?.title || ""}
                description={activeVideo?.subtitle}
            />
        </section>
    );
}

// ------ Individual Video Card Component ------
interface VideoCardProps {
    video: VideoItem;
    isActive: boolean;
    onMouseEnter: () => void;
    onFocus: () => void;
    onClick: () => void;
}

function VideoCard({ video, isActive, onMouseEnter, onFocus, onClick }: VideoCardProps) {
    const videoRef = useRef<HTMLVideoElement>(null);
    const playTimeoutRef = useRef<NodeJS.Timeout | null>(null);
    const prefersReducedMotion = useReducedMotion();

    // Handle Autoplay for active card
    useEffect(() => {
        if (isActive && !prefersReducedMotion && video.previewVideoSrc) {
            // Small delay before playing
            playTimeoutRef.current = setTimeout(() => {
                if (videoRef.current) {
                    videoRef.current.play().catch(() => {
                        // Silently ignore play errors (e.g., interrupted by user interaction)
                    });
                }
            }, 250);
        } else {
            if (playTimeoutRef.current) clearTimeout(playTimeoutRef.current);
            if (videoRef.current) {
                videoRef.current.pause();
                videoRef.current.currentTime = 0;
            }
        }

        return () => {
            if (playTimeoutRef.current) clearTimeout(playTimeoutRef.current);
        };
    }, [isActive]);

    return (
        <motion.button
            layout
            onMouseEnter={onMouseEnter}
            onFocus={onFocus}
            onClick={onClick}
            className={`relative rounded-2xl md:rounded-3xl overflow-hidden shadow-sm hover:shadow-lg transition-shadow group flex-shrink-0 focus:outline-none focus-visible:ring-4 focus-visible:ring-blue-500 focus-visible:ring-offset-4 focus-visible:ring-offset-white snap-center
        ${isActive ? "md:flex-1 w-[85vw] sm:w-[70vw] md:w-auto h-full cursor-pointer" : "md:w-40 lg:w-48 w-[70vw] sm:w-[50vw] h-full md:h-full cursor-pointer"}
      `}
            transition={{
                type: prefersReducedMotion ? "tween" : "spring",
                bounce: 0.2,
                duration: prefersReducedMotion ? 0.3 : 0.8
            }}
            aria-label={`Play ${video.title} video`}
            role="button"
        >
            {/* Background / Poster */}
            <motion.div layout className="absolute inset-0 w-full h-full">
                <img
                    src={video.posterImage}
                    alt=""
                    className="w-full h-full object-cover"
                    loading="lazy"
                />
            </motion.div>

            {/* Video Preview */}
            <div className={`absolute inset-0 transition-opacity duration-700 pointer-events-none overflow-hidden ${isActive ? 'opacity-100' : 'opacity-0'}`}>
                {video.previewVideoSrc ? (
                    video.previewVideoSrc.includes("youtube.com") ? (
                        isActive && !prefersReducedMotion ? (
                            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[300%] h-[300%] md:w-[200%] md:h-[200%] pointer-events-none flex items-center justify-center">
                                <iframe
                                    src={video.previewVideoSrc}
                                    className="w-full h-full border-0 pointer-events-none bg-black max-w-none scale-[1.3]"
                                    style={{ aspectRatio: "16/9", minWidth: "100%", minHeight: "100%" }}
                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                    tabIndex={-1}
                                />
                            </div>
                        ) : null
                    ) : (
                        <video
                            ref={videoRef}
                            src={video.previewVideoSrc}
                            className="w-full h-full object-cover"
                            playsInline
                            muted
                            loop
                            preload="none"
                        />
                    )
                ) : null}
            </div>

            {/* Gradient Overlay for Text Visibility */}
            <div
                className={`absolute inset-0 bg-gradient-to-t transition-all duration-500 
          ${isActive
                        ? "from-black/80 via-black/30 to-black/10 opacity-100"
                        : "from-black/60 to-black/10 opacity-80 group-hover:opacity-100"}
        `}
            />

            {/* Content Overlay */}
            <div className="absolute inset-0 p-4 md:p-8 flex flex-col justify-end text-left z-10">
                <AnimatePresence mode="popLayout">
                    {isActive ? (
                        <motion.div
                            layoutId={`content-${video.id}`}
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: 10 }}
                            transition={{ duration: 0.3, delay: 0.1 }}
                            className="flex w-full items-end justify-between gap-4"
                        >
                            <div className="max-w-[85%] pr-4 drop-shadow-md">
                                <p className="text-white/80 font-medium text-xs md:text-sm mb-1.5 md:mb-2 tracking-wide uppercase">{video.duration && `${video.duration} • `}{video.category}</p>
                                <h3 className="text-xl md:text-3xl font-bold text-white leading-tight mb-1.5 md:mb-2">
                                    {video.title}
                                </h3>
                                {video.subtitle && (
                                    <p className="text-white/90 text-sm md:text-base line-clamp-2">
                                        {video.subtitle}
                                    </p>
                                )}
                            </div>

                            {/* Play Button */}
                            <div className="bg-white/95 group-hover:bg-white text-blue-600 rounded-full p-3 md:p-4 flex-shrink-0 shadow-xl shadow-black/30 transition-all transform group-hover:scale-110 mb-1 md:mb-2">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" className="w-5 h-5 md:w-6 md:h-6">
                                    <path d="M5.5 3.5L19.5 12L5.5 20.5V3.5Z" />
                                </svg>
                            </div>
                        </motion.div>
                    ) : (
                        <motion.div
                            layoutId={`content-${video.id}`}
                            className="w-full flex items-end justify-start h-full drop-shadow-md"
                        >
                            <h3 className="text-white font-semibold text-base md:text-lg leading-snug line-clamp-2 md:whitespace-normal">
                                {video.title}
                            </h3>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </motion.button>
    );
}
