import { Command } from 'commander';
import OpenAI from 'openai';
import * as fs from 'fs';
import * as path from 'path';

const program = new Command();
program
  .requiredOption('-f, --file <path>', 'Path to the article-blueprints.md file generated by the SEO agent')
  .option('-m, --mock', 'Run in mock mode without calling OpenAI API')
  .parse(process.argv);

const options = program.opts();

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const EXBABEL_CONTEXT = `
Exbabel is an AI-powered real-time translation and captioning SaaS platform designed specifically for churches, ministries, and live events. 
It supports 180+ languages, uses a context-aware AI engine (trained on theological phrases and Bible verses), and requires no app downloads—attendees simply scan a QR code to listen to translated audio or read live captions on their phones.
Key selling points: affordability, no hardware, speech-to-speech voice cloning, and easy integration with OBS/livestreams.
`;

const AUTHENTICITY_SIGNALS = `
You MUST inject these "Signals of Authentic Content" to create an SEO moat:
- First-Person Experience: Use "we" or "I" narratives (e.g. "We tested Exbabel at our church...").
- Specific Details: Use concrete numbers, dates, real church/event names.
- Verifiable Data: Cite real stats, studies, or Exbabel's internal benchmarks.
- Quotation and Attribution: Quote a pastor, AV director, or specific Scripture.
- Depth vs Fluff: Address technical nuances (audio latency, Wi-Fi needs) and honest limitations.
`;

const SCORING_RUBRIC = `
100-Point Scoring Rubric (10 points each):
1. Originality: Unique angle or insight.
2. First-Person Experience: Authentic perspective used.
3. Specificity: Concrete numbers and facts.
4. Evidence/Trust: External citations or data included.
5. Narrative Quality: Engaging story structure.
6. SEO Strength: Target keyword optimized well.
7. Conversion Potential: Strong CTA included.
8. AI Citation Potential: Contains quotable facts/tables for AI bots.
9. Difficulty-to-Replicate: Proprietary angle used.
10. Overall Impact: Cohesion and clarity.
`;

async function main() {
  const filePath = path.resolve(options.file);
  console.log(`\n🚀 Starting Exbabel Batch Article Generator`);
  console.log(`📂 Reading blueprints from: ${filePath}`);

  if (!fs.existsSync(filePath)) {
    console.error(`❌ File not found: ${filePath}`);
    process.exit(1);
  }

  const fileContent = fs.readFileSync(filePath, 'utf-8');
  // The briefs are separated by "---" in the markdown
  const briefChunks = fileContent.split(/\n\n---\n\n/);
  
  // Filter out any small intro chunks
  const validBriefs = briefChunks.filter(c => c.length > 200);

  console.log(`📝 Found ${validBriefs.length} article blueprints to process.`);

  const outputDir = path.join(path.dirname(filePath), 'generated-articles');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  for (let i = 0; i < validBriefs.length; i++) {
    const brief = validBriefs[i];
    console.log(`\n======================================================`);
    console.log(`⚙️  Processing Article ${i + 1} of ${validBriefs.length}...`);

    if (options.mock) {
      console.log('   [MOCK] Skipping OpenAI generation...');
      continue;
    }

    // Step 1: Framework Selection
    console.log('   ✓ Selecting Article Framework based on the brief...');
    const frameworkResponse = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: `You are Exbabel's Content Strategist.` },
        { role: 'user', content: `Review this SEO Content Brief:\n\n${brief.substring(0, 1000)}...\n\nSelect the best journalistic/marketing framework from this list:
Informational: Ultimate Guide, How-To Tutorial, FAQ Guide, Data Visualization Story, Investigative Report.
Commercial: Case Study, Founder Story, Product Comparison, Listicle, Review.
Transactional: PAS (Problem-Agitate-Solve), AIDA, Before-After-Bridge.

Return ONLY the exact name of the chosen framework and nothing else.` }
      ]
    });
    const frameworkSelection = frameworkResponse.choices[0].message.content || 'Ultimate Guide';
    console.log(`     -> Selected Framework: ${frameworkSelection}`);

    // Step 2: Full Article Generation
    console.log('   ✓ Drafting the Full Article (Injecting authenticity signals)...');
    const articleResponse = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: `You are an expert Church-Tech Journalist and Conversion Copywriter. ${EXBABEL_CONTEXT}` },
        { role: 'user', content: `Write a massive, comprehensive 1,500+ word article based on this 25-point SEO blueprint:

${brief}

CRITICAL RULES:
${AUTHENTICITY_SIGNALS}
- Framework to follow: ${frameworkSelection}
- Use Markdown formatting.
- Include a comparison table or data chart if applicable (this increases AI citation potential).
- Include an FAQ section with short, direct answers (for Featured Snippets).
- End with a strong conversion CTA for Exbabel.` }
      ]
    });
    const fullArticle = articleResponse.choices[0].message.content || '';

    // Step 3: Entity Extraction & Internal Linking Engine
    console.log('   ✓ Entity Extraction & Internal Linking Engine...');
    const entityResponse = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: `You are Exbabel's Internal Linking Engine.` },
        { role: 'user', content: `Take the following article draft. Extract key entities (e.g. "Simultaneous Interpretation", "Church Translation", "Live Captioning") and wrap them in markdown internal links (e.g. [Simultaneous Interpretation](/simultaneous-interpretation)). Ensure no broken links and only link the first mention of an entity.
        
Article Draft:
${fullArticle}

Return ONLY the newly linked article text.` }
      ]
    });
    const linkedArticle = entityResponse.choices[0].message.content || fullArticle;

    // Step 4: Rubric Scoring
    console.log('   ✓ Editor Review: Scoring the draft against the 100-Point Rubric...');
    const scoreResponse = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: `You are Exbabel's Managing Editor.` },
        { role: 'user', content: `Evaluate this article against our 100-Point Scoring Rubric.

${SCORING_RUBRIC}

Article Draft:
${linkedArticle}

Provide the score for each of the 10 categories, then the total score, and 3 specific bullet points for improvement.` }
      ]
    });
    const scoreReport = scoreResponse.choices[0].message.content || '';

    // Extract a safe filename from the first line or two of the brief
    const titleMatch = brief.match(/Primary Keyword:\s*(.+)/i) || brief.match(/Keyword:\s*(.+)/i) || brief.match(/(.+)/);
    const safeTitle = titleMatch ? titleMatch[1].replace(/[^a-z0-9]/gi, '-').toLowerCase().substring(0, 50) : `article-${i+1}`;
    
    // Step 5: Save Output
    const finalOutput = `# Content Generation Report\n**Framework Selected:** ${frameworkSelection}\n\n---\n\n## 1. Article Draft\n${linkedArticle}\n\n---\n\n## 2. Editor's Rubric Score (100-Points)\n${scoreReport}\n`;

    const outputPath = path.join(outputDir, `${safeTitle}.md`);
    fs.writeFileSync(outputPath, finalOutput);
    console.log(`   ✓ Article successfully generated and saved to: ${outputPath}`);
  }
  
  console.log(`\n🎉 Batch processing complete! All articles saved to: ${outputDir}`);
}

main().catch(console.error);
