import { Command } from 'commander';
import OpenAI from 'openai';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import {
  selectPermutationForKeyword,
  parseArticleBlueprint,
  buildArticleFromFrameworkSpec,
  evaluateArticleRubric,
  injectEntityInternalLinks,
  AUTHENTICITY_SIGNALS_CHECKLIST,
  getChurchProfileForKeyword
} from './frameworks-library';

dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const program = new Command();
program
  .requiredOption('-f, --file <path>', 'Path to the article-blueprints.md file generated by the SEO agent')
  .option('-m, --mock', 'Run in mock mode without calling external AI APIs')
  .option('-p, --provider <provider>', 'AI provider to use: openai, claude, or auto', 'auto')
  .parse(process.argv);

const options = program.opts();

const openaiKey = process.env.OPENAI_API_KEY;
const anthropicKey = process.env.ANTHROPIC_API_KEY;

const openai = new OpenAI({
  apiKey: openaiKey || 'dummy_key_for_mock_mode',
});

const EXBABEL_CONTEXT = `
Exbabel (exbabel.com) is an AI-powered real-time translation and captioning SaaS platform designed specifically for churches, ministries, and live events. 
It supports 180+ languages, uses a context-aware AI engine (trained on theological phrases and Bible verses), and requires no app downloads—attendees simply scan a QR code to listen to translated audio or read live captions on their phones.
Key selling points: sub-second (<0.8s) audio latency, $24-$99/mo affordability, zero receiver hardware, speech-to-speech voice cloning, and easy integration with soundboards, OBS, and ProPresenter 7.
`;

async function callClaudeAPI(systemPrompt: string, userPrompt: string): Promise<string> {
  if (!anthropicKey) {
    throw new Error('ANTHROPIC_API_KEY is not set in environment or .env.local');
  }

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': anthropicKey,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 4000,
      system: systemPrompt,
      messages: [
        { role: 'user', content: userPrompt }
      ]
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Claude API request failed (${response.status}): ${errText}`);
  }

  const data = await response.json();
  return data.content[0]?.text || '';
}

async function generateArticleWithAI(
  systemPrompt: string,
  userPrompt: string,
  provider: string
): Promise<string> {
  const useClaude = (provider === 'claude') || (provider === 'auto' && anthropicKey && !openaiKey);
  
  if (useClaude) {
    console.log('      [LLM] Calling Claude API (Claude 3.5 Sonnet / Opus)...');
    return await callClaudeAPI(systemPrompt, userPrompt);
  } else {
    console.log('      [LLM] Calling OpenAI API (GPT-4o)...');
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.7
    });
    return response.choices[0].message.content || '';
  }
}

async function main() {
  const filePath = path.resolve(options.file);
  console.log(`\n🚀 Starting Exbabel Batch Article Generator (50+ Frameworks Permutation Engine)`);
  console.log(`📂 Reading blueprints from: ${filePath}`);

  if (!fs.existsSync(filePath)) {
    console.error(`❌ File not found: ${filePath}`);
    process.exit(1);
  }

  const fileContent = fs.readFileSync(filePath, 'utf-8');
  let briefChunks = fileContent
    .split(/(?=\n# (?:Content Brief|Master SEO Content Package|Article Blueprint|Brief|Article:):)/i)
    .map(c => c.trim())
    .filter(c => c.length > 150);

  if (briefChunks.length === 0) {
    briefChunks = fileContent.split(/\n\n---\n\n/).filter(c => c.length > 150);
  }

  console.log(`📝 Found ${briefChunks.length} article blueprints to process.`);

  const outputDir = path.join(path.dirname(filePath), 'generated-articles');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  for (let i = 0; i < briefChunks.length; i++) {
    const brief = briefChunks[i];
    console.log(`\n======================================================`);
    console.log(`⚙️  Processing Article ${i + 1} of ${briefChunks.length}...`);

    const parsedBlueprint = parseArticleBlueprint(brief);
    const kwRaw = parsedBlueprint.kwRaw;
    const persona = parsedBlueprint.persona;
    const intent = parsedBlueprint.intent;
    const safeTitle = kwRaw.toLowerCase().replace(/[^a-z0-9]/gi, '-').replace(/-+/g, '-').substring(0, 50);

    // 1. PERMUTATION SELECTION ENGINE (4-TUPLE PERMUTATION)
    const permutation = selectPermutationForKeyword(kwRaw, intent, persona);
    const framework = permutation.framework;
    const profile = getChurchProfileForKeyword(kwRaw);

    console.log(`   ✓ [Phase 1: Content Brief & Permutation Tuple Selected]:`);
    console.log(`       • Target Keyword: "${kwRaw}" (${persona} | ${intent})`);
    console.log(`       • Article Framework (1/4): "${permutation.framework.name}" (${permutation.framework.category})`);
    console.log(`       • Case-Study Variation (2/4): "${permutation.caseStudyVariation.name}"`);
    console.log(`       • SEO Structure (3/4): "${permutation.seoStructure.name}"`);
    console.log(`       • Applied Patterns (4/4): ${permutation.promptPatterns.map(p => p.name).join(', ')}`);

    let rawArticleText = '';
    let linkedArticle = '';
    let scoreReportMarkdown = '';

    if (options.mock) {
      console.log(`   [Phase 2 & 3: Blueprint-Driven Permutation Generation]: Building 2,500+ word article...`);
      linkedArticle = buildArticleFromFrameworkSpec(permutation, kwRaw, persona, intent, brief);
    } else {
      console.log(`   ✓ [Phase 2: Authenticity Injection & Blueprint Prompt Synthesis]...`);
      
      const authenticityRequirements = AUTHENTICITY_SIGNALS_CHECKLIST.map(s => `- **${s.name}**: ${s.instruction}`).join('\n');
      const patternGuidance = permutation.promptPatterns.map(p => `- **${p.name}**: ${p.description}`).join('\n');
      const headingsList = parsedBlueprint.headings.map(h => `- ${h.level}: ${h.text}`).join('\n');

      const systemPrompt = `You are a Senior Church-Tech Journalist and Lead B2B SaaS Copywriter writing for Exbabel. ${EXBABEL_CONTEXT}`;

      const userPrompt = `Write an EXHAUSTIVE 2,800+ word article for primary keyword: "${kwRaw}".

SEO CONTENT BRIEF INSTRUCTIONS (MUST FOLLOW STRUCTURAL HEADINGS EXACTLY):
- Target Keyword: ${kwRaw}
- H1 Title Tag: ${parsedBlueprint.h1Title}
- Target Word Count: ${parsedBlueprint.targetWordCount}
- Buyer Persona: ${persona}
- Search Intent: ${intent}

EXACT HEADINGS TO USE IN ARTICLE (DO NOT CHANGE OR OMIT THESE HEADINGS):
${headingsList}

PAA FAQ TARGET QUESTIONS (TO ANSWER IN FAQ SECTION):
${parsedBlueprint.paaQuestions.map(q => `- ${q}`).join('\n')}

INTERNAL LINKS TO EMBED NATURALLY:
${parsedBlueprint.internalLinks.map(l => `- ${l}`).join('\n')}

WRITING STYLE & PERMUTATION FRAMEWORK (LENS & TONE):
You must write the entire article following the structural headings above, applying this 4-Tuple Permutation as your writing style, perspective, and positioning lens:
- Framework Lens: ${permutation.framework.name} (${permutation.framework.category}) - ${permutation.framework.whyItWorks}
- Case-Study Angle: ${permutation.caseStudyVariation.name}
- SEO Structure: ${permutation.seoStructure.name}
- Applied Patterns: ${permutation.promptPatterns.map(p => p.name).join(', ')}

CHURCH CONTEXT:
- Church: ${profile.name} (${profile.location})
- Leader: ${profile.leader} (${profile.role})
- Soundboard: ${profile.soundboard}
- Target Languages: ${profile.languages}

AUTHENTICITY SIGNALS (CHECKLIST TO INJECT):
${authenticityRequirements}

APPLIED PROMPT PATTERNS:
${patternGuidance}

STRICT QUALITY RULES:
1. Write 400-600 words of dedicated, deep prose under EVERY heading from the brief.
2. DO NOT repeat paragraphs or boilerplate text across headings. Every section must deliver unique, authoritative technical and pastoral analysis.
3. Incorporate real audio engineering concepts (soundboard aux routing, gain staging, high-pass filtering at 80 Hz, Opus audio codec, sub-second <0.8s latency).
4. Embed internal links using standard markdown syntax: [anchor text](${parsedBlueprint.internalLinks[0] || '/pricing'}).
5. DO NOT print internal prompt names or framework identifiers (e.g., "Framework Specification 27", "Case Study Variation 40") anywhere in the article headers or body text. Apply the framework as your writing lens and style, NOT as text content.

Output ONLY clean production-ready Markdown formatting.`;

      rawArticleText = await generateArticleWithAI(systemPrompt, userPrompt, options.provider);
      
      console.log('   ✓ [Phase 3: Entity Engine & Internal Linking]...');
      linkedArticle = injectEntityInternalLinks(rawArticleText);
    }

    // 4. RUBRIC SCORING EVALUATOR (100-Point Scale)
    console.log('   ✓ [Phase 4: Managing Editor 100-Point Rubric Scoring]...');
    const evalResult = evaluateArticleRubric(linkedArticle, framework);

    scoreReportMarkdown = `### 📝 Managing Editor 100-Point Rubric Evaluation (Grade: ${evalResult.grade})
- **Originality (0-10)**: ${evalResult.breakdown.originality}/10
- **First-Person Experience (0-10)**: ${evalResult.breakdown.firstPersonExperience}/10
- **Specificity & Specs (0-10)**: ${evalResult.breakdown.specificity}/10
- **Evidence & Data Trust (0-10)**: ${evalResult.breakdown.evidenceTrust}/10
- **Narrative Quality (0-10)**: ${evalResult.breakdown.narrativeQuality}/10
- **SEO Strength & Length (0-10)**: ${evalResult.breakdown.seoStrength}/10
- **Conversion Potential (0-10)**: ${evalResult.breakdown.conversionPotential}/10
- **AI Citation Potential (0-10)**: ${evalResult.breakdown.aiCitationPotential}/10
- **Moat Factor (0-10)**: ${evalResult.breakdown.moatFactor}/10
- **Overall Impact (0-10)**: ${evalResult.breakdown.overallImpact}/10
- **Total Score**: **${evalResult.totalScore}/100**

> **Editor Summary**: ${evalResult.summary}`;

    const finalOutput = `# Article: ${kwRaw.toUpperCase()}

**SEO Blueprint Target Keyword:** ${kwRaw}  
**Buyer Persona:** ${persona} | **Search Intent:** ${intent}  
**Target Word Count:** ${parsedBlueprint.targetWordCount} | **URL Slug:** ${parsedBlueprint.urlSlug}  

**Permutation Tuple (Writing Lens):**  
- **Article Framework:** ${permutation.framework.name} (${permutation.framework.category})  
- **Case-Study Variation:** ${permutation.caseStudyVariation.name}  
- **SEO Structure:** ${permutation.seoStructure.name}  
- **Applied Patterns:** ${permutation.promptPatterns.map(p => p.name).join(', ')}  

---

${linkedArticle}

---

## 📝 Managing Editor Review & Rubric Score

${scoreReportMarkdown}
`;

    const outputPath = path.join(outputDir, `${safeTitle}.md`);
    fs.writeFileSync(outputPath, finalOutput);
    console.log(`   ✓ Article saved to: ${outputPath}`);
  }

  console.log(`\n🎉 Batch processing complete! All framework-driven articles saved to: ${outputDir}`);
}

main().catch(console.error);
